<?php

class Adherent extends Objet
{

    protected static $objet = "Adherent";
    protected static $cle = "login";
    protected $login;
    protected $mdp;
    protected $nomAdherent;
    protected $prenomAdherent;
    protected $email;
    protected $dateAdhesion;
    protected $numCategorie;

    public function afficher(){
        return $this->get('nomAdherent') . " " . $this->get('prenomAdherent') . " : " . $this->get('dateAdhesion') . " (" . $this->get('login') . "," . $this->get('mdp') . ")";
    }

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }

}