<?php

class Adherent extends Objet
{

    protected static $objet = "Adherent";
    protected static $cle = "login";
    protected $login;
    protected $mdp;
    protected $nomAdherent;
    protected $prenomAdherent;
    protected $email;
    protected $dateAdhesion;
    protected $numCategorie;

    public function afficher(){
        return $this->get('nomAdherent') . " " . $this->get('prenomAdherent') . " : " . $this->get('dateAdhesion') . " (" . $this->get('login') . "," . $this->get('mdp') . ")";
    }

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }

    public static function addAdherent($login, $mdp, $nom, $prenom, $email, $dateAdhesion){
        $requete = "INSERT INTO Adherent (login, mdp, nomAdherent, prenomAdherent, email, dateAdhesion, numCategorie) VALUES (:login, :mdp, :nomAdherent, :prenomAdherent, :email, :dateAdhesion, 1)";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "login" => $login,
            "mdp" => $mdp,
            "nomAdherent" => $nom,
            "prenomAdherent" => $prenom,
            "email" => $email,
            "dateAdhesion" => $dateAdhesion,
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur d'ajout : " . $e->getMessage();
            return false;
        }
    }

    public static function updateAdherent($login, $mdp, $nom, $prenom, $email, $dateAdhesion){
        $requete = "UPDATE Adherent SET mdp = :mdp, nomAdherent = :nomAdherent, prenomAdherent = :prenomAdherent, email = :email, dateAdhesion = :dateAdhesion, numCategorie = 1 WHERE login = :login";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "login" => $login,
            "mdp" => $mdp,
            "nomAdherent" => $nom,
            "prenomAdherent" => $prenom,
            "email" => $email,
            "dateAdhesion" => $dateAdhesion,
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur de modification : " . $e->getMessage();
            return false;
        }
    }

}