<?php

class Auteur extends Objet {

// attributs
	protected static $objet = "Auteur";
	protected static $cle = "numAuteur";
	protected $numAuteur;
	protected $nom;
	protected $prenom;
	protected $anneeNaissance;

	public function get($attribut)
	{
		return parent::get($attribut); // TODO: Change the autogenerated stub
	}

	public function set($attribut, $valeur)
	{
		parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
	}

	public function __construct($data = NULL)
	{
		parent::__construct($data);
	}

	public function afficher() {
		echo "<p>$this->prenom $this->nom, né(e) en $this->anneeNaissance </p>";
	}
}
?>
