<?php

class Auteur extends Objet {

// attributs
	protected static $objet = "Auteur";
	protected static $cle = "numAuteur";
	protected $numAuteur;
	protected $nom;
	protected $prenom;
	protected $anneeNaissance;

	public function get($attribut)
	{
		return parent::get($attribut); // TODO: Change the autogenerated stub
	}

	public function set($attribut, $valeur)
	{
		parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
	}

	public function __construct($data = NULL)
	{
		parent::__construct($data);
	}

	public static function addAuteur($nom, $prenom, $naissance){
		$requete = "INSERT INTO Auteur (nom, prenom, anneeNaissance) VALUES (:nom, :prenom, :anneeNaissance)";
		$req_prep = Connexion::pdo()->prepare($requete);
		$tab = array(
			"nom" => $nom,
			"prenom" => $prenom,
			"anneeNaissance" => $naissance
		);
		try {
			$req_prep->execute($tab);
			return true;
		} catch (PDOException $e) {
			echo "Erreur d'ajout : " . $e->getMessage();
			return false;
		}
	}

	// update auteur
	public static function updateAuteur($numAuteur, $nom, $prenom, $anneeNaissance){
		$requete = "UPDATE Auteur SET nom = :nom, prenom = :prenom, anneeNaissance = :anneeNaissance WHERE numAuteur = :numAuteur";
		$req_prep = Connexion::pdo()->prepare($requete);
		$tab = array(
			"numAuteur" => $numAuteur,
			"nom" => $nom,
			"prenom" => $prenom,
			"anneeNaissance" => $anneeNaissance
		);
		try {
			$req_prep->execute($tab);
			return true;
		} catch (PDOException $e) {
			echo "Erreur de modification : " . $e->getMessage();
			return false;
		}
	}
}
?>
