<?php

class Categorie extends Objet
{

    protected $numCategorie;
    protected $libelle;
    protected $nbLivresAutorises;
    protected static $cle = "numCategorie";
    protected static $objet = "Categorie";

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }

    // afficher
    public function afficher(){
        return $this->get('libelle');
    }

    public static function updateCategorie($numCategorie, $libelle, $nbLivresAutorises){
        $requete = "UPDATE Categorie SET libelle = :libelle, nbLivresAutorises = :nbLivresAutorises WHERE numCategorie = :numCategorie";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "numCategorie" => $numCategorie,
            "libelle" => $libelle,
            "nbLivresAutorises" => $nbLivresAutorises
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur de modification : " . $e->getMessage();
            return false;
        }
    }

}