<?php

class DateEmprunt extends Objet
{

    private $numDateEmprunt;
    private $dateEmprunt;
    protected static $objet = "dateEmprunt";

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }

}