<?php
class Genre extends Objet {

    // Properties
    protected $numGenre;
    protected $intitule;
    protected static $cle = "numGenre";
    protected static $objet = "Genre";

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }

    public static function addGenre($intitule){
        $requete = "INSERT INTO Genre (intitule) VALUES (:intitule)";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "intitule" => $intitule
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur d'ajout : " . $e->getMessage();
            return false;
        }
    }

    public static function updateGenre($numGenre, $intitule){
        $requete = "UPDATE Genre SET intitule = :intitule WHERE numGenre = :numGenre";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "numGenre" => $numGenre,
            "intitule" => $intitule
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur de modification : " . $e->getMessage();
            return false;
        }
    }
}