<?php

class Livre extends Objet
{
    protected static $objet = "Livre";
    protected static $cle = "numLivre";
    protected $numLivre;
    protected $titre;
    protected $anneeParution;
    protected $numGenre;

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function afficher(){
        return "[" . $this->get('numLivre') . "] " . $this->get('titre') . " " . $this->get('anneeParution') . " | Genre : " . $this->get('numGenre');
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }

    public static function addLivre($titre, $anneeParution, $numGenre){
        $requete = "INSERT INTO Livre (titre, anneeParution, numGenre) VALUES (:titre, :anneeParution, :numGenre)";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "titre" => $titre,
            "anneeParution" => $anneeParution,
            "numGenre" => $numGenre
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur d'ajout : " . $e->getMessage();
            return false;
        }
    }

    public static function updateLivre($numLivre, $titre, $anneeParution, $numGenre){
        $requete = "UPDATE Livre SET titre = :titre, anneeParution = :anneeParution, numGenre = :numGenre WHERE numLivre = :numLivre";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "numLivre" => $numLivre,
            "titre" => $titre,
            "anneeParution" => $anneeParution,
            "numGenre" => $numGenre
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur de modification : " . $e->getMessage();
            return false;
        }
    }
}