<?php

class Livre extends Objet
{
    protected static $objet = "Livre";
    protected static $cle = "numLivre";
    protected $numLivre;
    protected $titre;
    protected $anneeParution;
    protected $numGenre;

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function afficher(){
        return "[" . $this->get('numLivre') . "] " . $this->get('titre') . " " . $this->get('anneeParution') . " | Genre : " . $this->get('numGenre');
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }
}