<?php

class Nationalite extends Objet
{

    protected $numNationalite;
    protected $pays;
    protected $abrege;
    protected static $cle = "numNationalite";
    protected static $objet = "Nationalite";

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }

    // afficher()
    public function afficher(){
        return $this->get('pays') . " [" . $this->get('abrege') . "]";
    }

    public static function addNationalite($pays, $abrege){
        $requete = "INSERT INTO Nationalite (pays, abrege) VALUES (:pays, :abrege)";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "pays" => $pays,
            "abrege" => $abrege
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur d'ajout : " . $e->getMessage();
            return false;
        }
    }

    public static function updateNationalite($numNationalite, $pays, $abrege){
        $requete = "UPDATE Nationalite SET pays = :pays, abrege = :abrege WHERE numNationalite = :numNationalite";
        $req_prep = Connexion::pdo()->prepare($requete);
        $tab = array(
            "numNationalite" => $numNationalite,
            "pays" => $pays,
            "abrege" => $abrege
        );
        try {
            $req_prep->execute($tab);
            return true;
        } catch (PDOException $e) {
            echo "Erreur de modification : " . $e->getMessage();
            return false;
        }
    }
}