<?php

class Nationalite extends Objet
{

    protected $numNationalite;
    protected $pays;
    protected $abrege;
    protected static $cle = "numNationalite";
    protected static $objet = "Nationalite";

    public function __construct($data = NULL)
    {
        parent::__construct($data);
    }

    public function get($attribut)
    {
        return parent::get($attribut); // TODO: Change the autogenerated stub
    }

    public function set($attribut, $valeur)
    {
        parent::set($attribut, $valeur); // TODO: Change the autogenerated stub
    }
}